#!/bin/bash

# MySQL database credentials
DB_USER="your_username"
DB_PASSWORD="your_password"
DB_NAME="your_database"

# SQL query to execute
SQL_QUERY="SELECT column1, column2, column3 FROM your_table;"

# Output CSV file name
CSV_FILE="output.csv"

# Execute the MySQL query and save the result as a CSV file
mysql -u "$DB_USER" -p"$DB_PASSWORD" -D "$DB_NAME" -B -e "$SQL_QUERY" | sed 's/\t/","/g;s/^/"/;s/$/"/;s/\n//g' > "$CSV_FILE"

echo "CSV file generated: $CSV_FILE"


send_email_with_attachment() {
    local subject="$1"
    local recipient="$2"
    local attachment="$3"

    # Compose the email
    echo "This is the body of the email." | mailx -s "$subject" -a "$attachment" "$recipient"
}



gzip_with_timestamp() {
    local original_file="$1"
    local timestamp=$(date +"%Y%m%d%H%M%S")
    local gzipped_file="${original_file%.${original_file##*.}}_$timestamp.gz"

    gzip "$original_file" -c > "$gzipped_file"
    echo "File '$original_file' has been gzipped as '$gzipped_file'."
}
